export default {
  name: "New Theme",
  background_colors_primary: "#F0F0F7",
  background_colors_secondary: "#66FF66",
  border_colors_primary: "#0000001A",
  icon_colors_menuItem: "#A5A4BF",
  icon_colors_activeMenuItem: "#66FF99",
  icon_colors_other_a: "#FFFFFF",
  icon_colors_other_b: "#56D9FE",
  icon_colors_other_c: "#A3A1FB",
  icon_colors_other_d: "#4AD991",
  icon_colors_other_e: "#A4AFB7",
  surface_colors_primary: "#FFFFFF",
  surface_boxShadows_primary: "#0000000A",
  tab_colors_primary: "#6441A5",
  tab_colors_secondary: "#66FF99",
  text_colors_primary: "#4D4F5C",
  text_colors_secondary: "#6441A5",
  text_colors_menuItem: "#FFFFFF",
  text_colors_other_a: "#000000",
  text_colors_other_b: "#56D9FE",
  text_colors_other_c: "#66FF99",
  text_colors_other_d: "#4AD991",
  text_colors_other_e: "#FF4141",
  text_colors_other_f: "#4D565C",
  text_colors_other_g: "#FCFCFC",
};
